### ISSUE TITLE
Cache not wotking with BuildKit

### ISSUE THREAD

**Issue by miroslav-chandler** [satackey/action-docker-layer-caching#117]
**Describe the bug**
Cache not working when building with DOCKER_BUILDKIT=1

**To Reproduce**
1. Build an image with BuildKit (put DOCKER_BUILDKIT=1 before build command)
2. Rebuild an image
3. An image is building from scratch, the cache is not used.

**Expected behavior**
An image is building from the cache.

**Debug logs**
In the logs I can see:
- cache is saved in the first iteration
- successfully fetched in the second, but image not using that cache.

**Runner Environment (please complete the following information):**
 - ubuntu-latest
 - satackey/action-docker-layer-caching@v0.0.11

**Additional context**
But it works ok with default builder.

**Comment by rcowsill** [comment]
Yes, BuildKit uses a different caching system than the default builder. The BuildKit cache doesn't get populated automatically by image loads, instead there are some command line options to enable caching: https://docs.docker.com/engine/reference/commandline/build/#specifying-external-cache-sources.

At the moment this action doesn't support the BuildKit cache, and I don't think those command line options are sufficient to implement this action's workflow. The docs probably need updating to make it clear that BuildKit isn't supported.

**Comment by miroslav-chandler** [comment]
Thanks!
I missed that information when reading the docs.

Yes, it would be great if that information will exist in the docs of this action.

**Comment by memark** [comment]
Appears it's still not in the docs. I just spent half a day trying to figure out why the cache wasn't working at all for me. :(

**Comment by dang113108** [comment]
Yes, I think the docs need to be updated
