### ISSUE TITLE
How to clear a cache?

### ISSUE THREAD

**Issue by alanwilter** [satackey/action-docker-layer-caching#79]
I'm playing with `action-docker-layer-caching` and loving it.

However, now my cach had grown too big! I have one image, 2GB, that I don't need it anymore, however, restoring cache step wastes time loading it. How can I reset my caches and start as anew?

**Comment by rcowsill** [comment]
Unfortunately the cache API [doesn't support overwriting cache entries](https://github.com/actions/cache/issues/342) yet. For now your only option is to [change the cache key and restore-keys](https://github.com/satackey/action-docker-layer-caching#inputs).

This will create a new set of layer cache files that don't include that 2GB image (assuming it's not being used any more). The old cache files will still exist, but won't be loaded by the action. They'll be deleted in 7 days or once you've filled up the 5GB per-repo cache quota.

**Comment by alanwilter** [comment]
Thanks and good to know. The alternative is quite fine.
