### ISSUE TITLE
Cannot upload FROM scratch image layers

### ISSUE THREAD

**Issue by tyranron** [satackey/action-docker-layer-caching#95]
**Describe the bug**
CI jobs that build `FROM scratch` images somehow cannot upload the cache in a post-step.

**To Reproduce**
1. Create a job that builds `FROM scratch` Docker image.
2. Add caching with this GitHub Action.
3. See the error in post-step.

**Expected behavior**
Post-job should upload any created image layers normally.

**Debug logs**
See [this job](https://github.com/instrumentisto/medea/pull/162/checks?check_run_id=1558910959), for example, which builds [the following `Dockerfile`](https://github.com/instrumentisto/medea/blob/0d0cc44107686b223ed9337c8edf6d02fb1d662e/Dockerfile):
```
Post job cleanup.
/bin/sh -c docker save '3f268f2d8ff3' '3f268f2d8ff3' '2b70a2fe443f' '514da35d4c88' 'fefd7f81fbe8' '95639df9477e' '95639df9477e' '692f51822250' '3db404ba035e' 'cdcfd23e4908' '826fd23f771f' '732c2936ac34' '0de5f11e842a' 'f6b52a897a7a' '049db6664b91' 'b1e3431dab8c' 'd52551e23000' 'f60ff88094b2' '5a8f3a9c56ec' 'ab6d7b76b1b9' '7137860ffc6b' '738215c4d2d1' 'd46674d6250e' 'e7ee0c7daedd' '682140a99ed0' '4f49052e8448' 'f3bcd0fe7760' '5eca3e4a1aa2' 'c4e362ce9805' '4f7bef47a1b7' '4f7bef47a1b7' '4f7bef47a1b7' 'instrumentisto/medea:build-49' '3f268f2d8ff3' '2b70a2fe443f' '514da35d4c88' 'fefd7f81fbe8' 'rust:1.48' '4f7bef47a1b7' | tar xf - -C .
Error response from daemon: empty export - not implemented
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Error: The process '/bin/sh' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.11/dist/ttsc-dist/post.js/index.js:1035:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.11/dist/ttsc-dist/post.js/index.js:1018:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.11/dist/ttsc-dist/post.js/index.js:912:27)
    at ChildProcess.emit (events.js:210:5)
Error: Error: The process '/bin/sh' failed with exit code 2
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
```

**Comment by tyranron** [comment]
It seems the something is wrong with `docker save` command. 

However, if I try `docker save -o my.tar instrumentisto/medea:some-tag` locally, the it archives OK.

**Comment by rcowsill** [comment]
It's related to this docker daemon issue: https://github.com/moby/moby/issues/38039

If the first line after `FROM scratch` doesn't modify the filesystem, that line creates an image with no layer content. `docker save` doesn't handle such images, resulting in this error. I reproduced that with a minimal test case locally so it seems to be correct.

Looking at the linked run log, it looks like the error happens after a docker build including this sequence of commands:
```
Step 26/30 : FROM scratch AS runtime
 ---> 
Step 27/30 : LABEL org.opencontainers.image.source="https://github.com/instrumentisto/medea"
 ---> Running in 0002cd378026
Removing intermediate container 0002cd378026
 ---> 0475b1a12b1a
Step 28/30 : COPY --from=dist /out/ /
 ---> 70ba4cd9a58b
```
I think moving that LABEL command after the COPY should work around the issue.

**Comment by tyranron** [comment]
@rcowsill thanks for the explanation. Will give that a try!

**Comment by tyranron** [comment]
Yup, that [has worked](https://github.com/instrumentisto/medea/pull/164/checks?check_run_id=1564243869)! @rcowsill thanks once again!

So, I'm closing this as we cannot do much with an upstream issue, and the workaround is given.
